name: own_inbox_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl_utils: ^2.8.1
  retrofit: ^3.3.1
  freezed: ^2.3.2
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  dio: ^4.0.6
  retrofit_generator: ^4.2.0
  flutter_bloc: ^8.1.1
  flutter_gen: ^5.1.0+1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Open Sans
     fonts:
       - asset: assets/fonts/OpenSans-ExtraBold.ttf
         weight: 800
       - asset: assets/fonts/OpenSans-Bold.ttf
         weight: 700
       - asset: assets/fonts/OpenSans-SemiBold.ttf
         weight: 600
       - asset: assets/fonts/OpenSans-Medium.ttf
         weight: 500
       - asset: assets/fonts/OpenSans-Regular.ttf
         weight: 400
       - asset: assets/fonts/OpenSans-Light.ttf
         weight: 300
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_intl:
  enabled: true
